name: system_info_demo
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
jobs:
  ll_demo:
    runs-on: ubuntu-22.04
    steps:
    - name: basic info
      run: pwd

    - name: clone and ll
      run: |
        git clone https://github.com/KittyKatt/screenFetch.git
        ls -al
        
    - name: tar
      run: |
        mkdir archieve
        cd ./archieve
        tar -zcvf test.tar ../screenFetch
    
    - name: ls too
      run: ls ./archieve
